In [2]:
from tensorflow import keras as ks
from matplotlib import pyplot as plt
import datetime as dt
import pandas
import plotly.express as px

In [3]:
path = "Energy_Consumption_Dataset/powerconsumption.csv"
ds = pandas.read_csv(path)

In [4]:
ds

,Datetime,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3
0,1/1/2017 0:00,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386
1,1/1/2017 0:10,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434
2,1/1/2017 0:20,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373
3,1/1/2017 0:30,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711
4,1/1/2017 0:40,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964
...,...,...,...,...,...,...,...,...,...
52411,12/30/2017 23:10,7.010,72.4,0.080,0.040,0.096,31160.45627,26857.31820,14780.31212
52412,12/30/2017 23:20,6.947,72.6,0.082,0.051,0.093,30430.41825,26124.57809,14428.81152
52413,12/30/2017 23:30,6.900,72.8,0.086,0.084,0.074,29590.87452,25277.69254,13806.48259
52414,12/30/2017 23:40,6.758,73.0,0.080,0.066,0.089,28958.17490,24692.23688,13512.60504
52415,12/30/2017 23:50,6.580,74.1,0.081,0.062,0.111,28349.80989,24055.23167,13345.49820

In [5]:
ds.describe().round(2)

,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3
count,52416.00,52416.00,52416.00,52416.00,52416.00,52416.00,52416.00,52416.00
mean,18.81,68.26,1.96,182.70,75.03,32344.97,21042.51,17835.41
std,5.82,15.55,2.35,264.40,124.21,7130.56,5201.47,6622.17
min,3.25,11.34,0.05,0.00,0.01,13895.70,8560.08,5935.17
25%,14.41,58.31,0.08,0.06,0.12,26310.67,16980.77,13129.33
50%,18.78,69.86,0.09,5.04,4.46,32265.92,20823.17,16415.12
75%,22.89,81.40,4.92,319.60,101.00,37309.02,24713.72,21624.10
max,40.01,94.80,6.48,1163.00,936.00,52204.40,37408.86,47598.33